name: JPackage Windows

on:
  release:
    types: [ released, prereleased ]

jobs:
  gradle:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: packageMsi
      - uses: softprops/action-gh-release@v1
        with:
          files: build/compose/binaries/main/msi/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}